// Code generated by mockery v1.0.0. DO NOT EDIT.

package arangomock

import driver "github.com/arangodb/go-driver"
import mock "github.com/stretchr/testify/mock"

// Authentication is an autogenerated mock type for the Authentication type
type Authentication struct {
	mock.Mock
}

// Get provides a mock function with given fields: property
func (_m *Authentication) Get(property string) string {
	ret := _m.Called(property)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(property)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Type provides a mock function with given fields:
func (_m *Authentication) Type() driver.AuthenticationType {
	ret := _m.Called()

	var r0 driver.AuthenticationType
	if rf, ok := ret.Get(0).(func() driver.AuthenticationType); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(driver.AuthenticationType)
	}

	return r0
}
