// Code generated by mockery v1.0.0. DO NOT EDIT.

package arangomock

import context "context"
import driver "github.com/arangodb/go-driver"
import mock "github.com/stretchr/testify/mock"

// ClientUsers is an autogenerated mock type for the ClientUsers type
type ClientUsers struct {
	mock.Mock
}

// CreateUser provides a mock function with given fields: ctx, name, options
func (_m *ClientUsers) CreateUser(ctx context.Context, name string, options *driver.UserOptions) (driver.User, error) {
	ret := _m.Called(ctx, name, options)

	var r0 driver.User
	if rf, ok := ret.Get(0).(func(context.Context, string, *driver.UserOptions) driver.User); ok {
		r0 = rf(ctx, name, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(driver.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, *driver.UserOptions) error); ok {
		r1 = rf(ctx, name, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// User provides a mock function with given fields: ctx, name
func (_m *ClientUsers) User(ctx context.Context, name string) (driver.User, error) {
	ret := _m.Called(ctx, name)

	var r0 driver.User
	if rf, ok := ret.Get(0).(func(context.Context, string) driver.User); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(driver.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserExists provides a mock function with given fields: ctx, name
func (_m *ClientUsers) UserExists(ctx context.Context, name string) (bool, error) {
	ret := _m.Called(ctx, name)

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Users provides a mock function with given fields: ctx
func (_m *ClientUsers) Users(ctx context.Context) ([]driver.User, error) {
	ret := _m.Called(ctx)

	var r0 []driver.User
	if rf, ok := ret.Get(0).(func(context.Context) []driver.User); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]driver.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
