// Code generated by mockery v1.0.0. DO NOT EDIT.

package arangomock

import context "context"
import driver "github.com/arangodb/go-driver"
import mock "github.com/stretchr/testify/mock"

// ClientCluster is an autogenerated mock type for the ClientCluster type
type ClientCluster struct {
	mock.Mock
}

// Cluster provides a mock function with given fields: ctx
func (_m *ClientCluster) Cluster(ctx context.Context) (driver.Cluster, error) {
	ret := _m.Called(ctx)

	var r0 driver.Cluster
	if rf, ok := ret.Get(0).(func(context.Context) driver.Cluster); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(driver.Cluster)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
