// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: pkg/instances/proto/instances.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// InstancesServiceClient is the client API for InstancesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InstancesServiceClient interface {
	Invoke(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (*InvokeResponse, error)
}

type instancesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInstancesServiceClient(cc grpc.ClientConnInterface) InstancesServiceClient {
	return &instancesServiceClient{cc}
}

func (c *instancesServiceClient) Invoke(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (*InvokeResponse, error) {
	out := new(InvokeResponse)
	err := c.cc.Invoke(ctx, "/nocloud.instances.InstancesService/Invoke", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InstancesServiceServer is the server API for InstancesService service.
// All implementations must embed UnimplementedInstancesServiceServer
// for forward compatibility
type InstancesServiceServer interface {
	Invoke(context.Context, *InvokeRequest) (*InvokeResponse, error)
	mustEmbedUnimplementedInstancesServiceServer()
}

// UnimplementedInstancesServiceServer must be embedded to have forward compatible implementations.
type UnimplementedInstancesServiceServer struct {
}

func (UnimplementedInstancesServiceServer) Invoke(context.Context, *InvokeRequest) (*InvokeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Invoke not implemented")
}
func (UnimplementedInstancesServiceServer) mustEmbedUnimplementedInstancesServiceServer() {}

// UnsafeInstancesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InstancesServiceServer will
// result in compilation errors.
type UnsafeInstancesServiceServer interface {
	mustEmbedUnimplementedInstancesServiceServer()
}

func RegisterInstancesServiceServer(s grpc.ServiceRegistrar, srv InstancesServiceServer) {
	s.RegisterService(&InstancesService_ServiceDesc, srv)
}

func _InstancesService_Invoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvokeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstancesServiceServer).Invoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nocloud.instances.InstancesService/Invoke",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstancesServiceServer).Invoke(ctx, req.(*InvokeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InstancesService_ServiceDesc is the grpc.ServiceDesc for InstancesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InstancesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nocloud.instances.InstancesService",
	HandlerType: (*InstancesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Invoke",
			Handler:    _InstancesService_Invoke_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/instances/proto/instances.proto",
}
