// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// StatesServiceClient is the client API for StatesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StatesServiceClient interface {
	PostState(ctx context.Context, in *PostStateRequest, opts ...grpc.CallOption) (*PostStateResponse, error)
	GetStates(ctx context.Context, in *GetStatesRequest, opts ...grpc.CallOption) (*GetStatesResponse, error)
}

type statesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStatesServiceClient(cc grpc.ClientConnInterface) StatesServiceClient {
	return &statesServiceClient{cc}
}

func (c *statesServiceClient) PostState(ctx context.Context, in *PostStateRequest, opts ...grpc.CallOption) (*PostStateResponse, error) {
	out := new(PostStateResponse)
	err := c.cc.Invoke(ctx, "/nocloud.states.StatesService/PostState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statesServiceClient) GetStates(ctx context.Context, in *GetStatesRequest, opts ...grpc.CallOption) (*GetStatesResponse, error) {
	out := new(GetStatesResponse)
	err := c.cc.Invoke(ctx, "/nocloud.states.StatesService/GetStates", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StatesServiceServer is the server API for StatesService service.
// All implementations must embed UnimplementedStatesServiceServer
// for forward compatibility
type StatesServiceServer interface {
	PostState(context.Context, *PostStateRequest) (*PostStateResponse, error)
	GetStates(context.Context, *GetStatesRequest) (*GetStatesResponse, error)
	mustEmbedUnimplementedStatesServiceServer()
}

// UnimplementedStatesServiceServer must be embedded to have forward compatible implementations.
type UnimplementedStatesServiceServer struct {
}

func (UnimplementedStatesServiceServer) PostState(context.Context, *PostStateRequest) (*PostStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostState not implemented")
}
func (UnimplementedStatesServiceServer) GetStates(context.Context, *GetStatesRequest) (*GetStatesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStates not implemented")
}
func (UnimplementedStatesServiceServer) mustEmbedUnimplementedStatesServiceServer() {}

// UnsafeStatesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StatesServiceServer will
// result in compilation errors.
type UnsafeStatesServiceServer interface {
	mustEmbedUnimplementedStatesServiceServer()
}

func RegisterStatesServiceServer(s grpc.ServiceRegistrar, srv StatesServiceServer) {
	s.RegisterService(&StatesService_ServiceDesc, srv)
}

func _StatesService_PostState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatesServiceServer).PostState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nocloud.states.StatesService/PostState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatesServiceServer).PostState(ctx, req.(*PostStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatesService_GetStates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatesServiceServer).GetStates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nocloud.states.StatesService/GetStates",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatesServiceServer).GetStates(ctx, req.(*GetStatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StatesService_ServiceDesc is the grpc.ServiceDesc for StatesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StatesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nocloud.states.StatesService",
	HandlerType: (*StatesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PostState",
			Handler:    _StatesService_PostState_Handler,
		},
		{
			MethodName: "GetStates",
			Handler:    _StatesService_GetStates_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/states/proto/states.proto",
}
